### PR TITLE
codespell: config, workflow and typos fixed

### PR DESCRIPTION
**Pull request by yarikoptic**
so upcoming release (#103) is shining with correctness! ;-)

### CODE REVIEW

**Comment by Remi-Gau** [comment]
I think I was too quick on #103...

**Comment by Remi-Gau** [comment]
probably worth adding a config file to ignore some words: see failure

**Comment by yarikoptic** [comment]
Added ignore, config is there https://github.com/neurodatascience/mr_proc/pull/104/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R5

**Review by Remi-Gau — APPROVED** [review]
LGTM thanks @yarikoptic

**Pull request merged**
